#!/usr/bin/env python3

import os
import code

JH_COMPUTE_BANNER = """
   __          ___                            _       
   \ \  /\  /\/ __\___  _ __ ___  _ __  _   _| |_ ___ 
    \ \/ /_/ / /  / _ \| '_ ` _ \| '_ \| | | | __/ _ \\
 /\_/ / __  / /__| (_) | | | | | | |_) | |_| | ||  __/
 \___/\/ /_/\____/\___/|_| |_| |_| .__/ \__,_|\__\___|
                                 |_|                  

          ~ By Sean Patterson & Billy Rooke ~
"""


def clear():
    os.system("cls" if os.name == "nt" else "clear")

def start_repl():
    code.interact(banner=JH_COMPUTE_BANNER, local=globals())

# initialising the environment

from jhcompute import *
start_repl()

# pool = JHCPool(20, "play.py")
# pool.queue("[{model1}, {model2}, {model3}]")
# some value back

