#!/usr/bin/env python3

import code

JH_COMPUTE_BANNER = """
   __          ___                            _       
   \ \  /\  /\/ __\___  _ __ ___  _ __  _   _| |_ ___ 
    \ \/ /_/ / /  / _ \| '_ ` _ \| '_ \| | | | __/ _ \\
 /\_/ / __  / /__| (_) | | | | | | |_) | |_| | ||  __/
 \___/\/ /_/\____/\___/|_| |_| |_| .__/ \__,_|\__\___|
                                 |_|                  

          ~ By Sean Patterson & Billy Rooke ~
"""


def start_repl():
    code.interact(banner=JH_COMPUTE_BANNER, local=globals())

# initialising the environment

a = 123

start_repl()
